# Generated by Django 5.1.6 on 2025-03-03 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='subtitle',
            field=models.CharField(default='ues', max_length=255),
            preserve_default=False,
        ),
    ]
