# Generated by Django 5.1.6 on 2025-03-03 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_opinion_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='subtitle',
            field=models.CharField(default='yes', max_length=255),
            preserve_default=False,
        ),
    ]
