# Generated by Django 5.1.6 on 2025-03-03 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_article_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
