# Generated by Django 5.1.6 on 2025-03-04 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_article_is_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opinion',
            name='subtitle',
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to='articles/'),
        ),
    ]
