# Generated by Django 5.1.6 on 2025-03-04 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_opinion_subtitle_alter_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='opinions/'),
        ),
    ]
